version: "3"
services:
  auth:
    build: ./nestjs-microservice-auth
    ports:
      - 3020:3020
    environment:
      AUTH_HOST: auth
      DB_NAME: "users"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "Arol3094"
  browserprofile:
    build: ./nestjs-microservice-browserprofile
    ports:
      - 3010:3010
    environment:
      BROWSER_PROFILE_HOST: browserprofile
      DB_NAME: "users"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "Arol3094"
  team:
    build: ./nestjs-microservice-team
    ports:
      - 3030:3030
    environment:
      TEAM_HOST: team
      DB_NAME: "users"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "Arol3094"
  teamlicense:
    build: ./nestjs-microservice-team-license
    ports:
      - 3040:3040
    environment:
      TEAM_LICENSE_HOST: team_license
      DB_NAME: "users"
      DB_HOST: "db"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "Arol3094"
  db:
    image: "postgres:12.1-alpine"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Arol3094"
      POSTGRES_DB: "users"
    healthcheck:
      test: ["CMD-SHELL", "su -c 'pg_isready -U postgres' postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: "on-failure"